{"name": "activecampaign", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: activecampaign_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"9f32dab3-77cb-45a1-9d33-347aa5fbe363\"}}\n"}
{"name": "airtable", "config_path": "config_oauth.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: airtable_config_oauth: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $.credentials: must be valid to one and only one schema, but 0 are valid, $.credentials: required property 'refresh_token' not found, $.credentials: required property 'api_key' not found \"}}\n"}
{"name": "alpha-vantage", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: alpha-vantage_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"db385323-9333-4fec-bec3-9e0ca9326c90\"}}\n"}
{"name": "amazon-seller-partner", "config_path": "config_old_data.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: amazon-seller-partner_config_old_data: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'account_type' not found \"}}\n"}
{"name": "appsflyer", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: appsflyer_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"16447954-e6a8-4593-b140-43dea13bc457\"}}\n"}
{"name": "avni", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: avni_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"avni\"}}\n"}
{"name": "azure-blob-storage", "config_path": "csv_no_header_config_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: azure-blob-storage_csv_no_header_config_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'credentials' not found \"}}\n"}
{"name": "breezometer", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: breezometer_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"7c37685e-8512-4901-addf-9afbef6c0de9\"}}\n"}
{"name": "callrail", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: callrail_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"dc98a6ad-2dd1-47b6-9529-2ec35820f9c6\"}}\n"}
{"name": "chargify", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: chargify_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"9b2d3607-7222-4709-9fa2-c2abdebbdd88\"}}\n"}
{"name": "coingecko-coins", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: coingecko-coins_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"9cdd4183-d0ba-40c3-aad3-6f46d4103974\"}}\n"}
{"name": "commercetools", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: commercetools_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"008b2e26-11a3-11ec-82a8-0242ac130003\"}}\n"}
{"name": "convertkit", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: convertkit_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"be9ee02f-6efe-4970-979b-95f797a37188\"}}\n"}
{"name": "copper", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: copper_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"44f3002f-2df9-4f6d-b21c-02cd3b47d0dc\"}}\n"}
{"name": "courier", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: courier_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"0541b2cd-2367-4986-b5f1-b79ff55439e4\"}}\n"}
{"name": "customer-io", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: customer-io_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"customer-io\"}}\n"}
{"name": "delighted", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: delighted_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $.since: does not match the date-time pattern must be a valid RFC 3339 date-time \"}}\n"}
{"name": "dixa", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: dixa_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $.start_date: does not match the date-time pattern must be a valid RFC 3339 date-time \"}}\n"}
{"name": "drift", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: drift_config: {\"status\":500,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"unexpected-problem\",\"detail\":\"An unexpected problem has occurred. If this is an error that needs to be addressed, please submit a pull request or github issue.\",\"documentationUrl\":null,\"data\":{\"message\":\"io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Secret Payload cannot be empty.\"}}\n"}
{"name": "drift", "config_path": "config_oauth.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: drift_config_oauth: {\"status\":500,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"unexpected-problem\",\"detail\":\"An unexpected problem has occurred. If this is an error that needs to be addressed, please submit a pull request or github issue.\",\"documentationUrl\":null,\"data\":{\"message\":\"io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Secret Payload cannot be empty.\"}}\n"}
{"name": "everhour", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: everhour_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"6babfc42-c734-4ef6-a817-6eca15f0f9b7\"}}\n"}
{"name": "fastbill", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: fastbill_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"eb3e9c1c-0467-4eb7-a172-5265e04ccd0a\"}}\n"}
{"name": "file", "config_path": "gcs.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: file_gcs: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'dataset_name' not found, $: required property 'format' not found, $: required property 'url' not found, $: required property 'provider' not found \"}}\n"}
{"name": "file", "config_path": "box_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: file_box_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'dataset_name' not found, $: required property 'format' not found, $: required property 'url' not found, $: required property 'provider' not found \"}}\n"}
{"name": "file", "config_path": "aws.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: file_aws: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'dataset_name' not found, $: required property 'format' not found, $: required property 'url' not found, $: required property 'provider' not found \"}}\n"}
{"name": "file", "config_path": "azblob.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: file_azblob: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'dataset_name' not found, $: required property 'format' not found, $: required property 'url' not found, $: required property 'provider' not found \"}}\n"}
{"name": "fleetio", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: fleetio_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"fleetio\"}}\n"}
{"name": "fullstory", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: fullstory_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"263fd456-02d1-4a26-a35e-52ccaedad778\"}}\n"}
{"name": "gong", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: gong_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"32382e40-3b49-4b99-9c5c-4076501914e7\"}}\n"}
{"name": "google-analytics-v4-service-account-only", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: google-analytics-v4-service-account-only_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"google-analytics-v4-service-account-only\"}}\n"}
{"name": "google-drive", "config_path": "oauth_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: google-drive_oauth_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"google-drive\"}}\n"}
{"name": "google-drive", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: google-drive_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"google-drive\"}}\n"}
{"name": "gutendex", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: gutendex_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"bff9a277-e01d-420d-81ee-80f28a307318\"}}\n"}
{"name": "harness", "config_path": "source-mongodb-v2_1m_credentials.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: harness_source-mongodb-v2_1m_credentials: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"harness\"}}\n"}
{"name": "harness", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: harness_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"harness\"}}\n"}
{"name": "harness", "config_path": "source-postgres_bottleneck_stream1_credentials.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: harness_source-postgres_bottleneck_stream1_credentials: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"harness\"}}\n"}
{"name": "harness", "config_path": "source-mysql_bottleneck_stream1_credentials.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: harness_source-mysql_bottleneck_stream1_credentials: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"harness\"}}\n"}
{"name": "harness", "config_path": "source-postgres_20m_credentials.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: harness_source-postgres_20m_credentials: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"harness\"}}\n"}
{"name": "harness", "config_path": "source-mysql_20m_credentials.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: harness_source-mysql_20m_credentials: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"harness\"}}\n"}
{"name": "harness", "config_path": "source-mysql_10m_credentials.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: harness_source-mysql_10m_credentials: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"harness\"}}\n"}
{"name": "harness", "config_path": "source-postgres_2b_credentials.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: harness_source-postgres_2b_credentials: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"harness\"}}\n"}
{"name": "harness", "config_path": "source-mysql_1m_credentials.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: harness_source-mysql_1m_credentials: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"harness\"}}\n"}
{"name": "harness", "config_path": "source-postgres_10m_credentials.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: harness_source-postgres_10m_credentials: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"harness\"}}\n"}
{"name": "harness", "config_path": "source-postgres_1m_credentials.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: harness_source-postgres_1m_credentials: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"harness\"}}\n"}
{"name": "hellobaton", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: hellobaton_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"492b56d1-937c-462e-8076-21ad2031e784\"}}\n"}
{"name": "intercom", "config_path": "config_apikey.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: intercom_config_apikey: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'access_token' not found \"}}\n"}
{"name": "intruder", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: intruder_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"3d15163b-11d8-412f-b808-795c9b2c3a3a\"}}\n"}
{"name": "jina-ai-reader", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: jina-ai-reader_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"jina-ai-reader\"}}\n"}
{"name": "klaus-api", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: klaus-api_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"klaus-api\"}}\n"}
{"name": "kyriba", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: kyriba_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"547dc08e-ab51-421d-953b-8f3745201a8c\"}}\n"}
{"name": "linnworks", "config_path": "dsdssds_a-b---_---_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: linnworks_dsdssds_a-b---_---_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'application_id' not found, $: required property 'application_secret' not found, $: required property 'token' not found, $: required property 'start_date' not found \"}}\n"}
{"name": "linnworks", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: linnworks_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $.start_date: does not match the date-time pattern must be a valid RFC 3339 date-time \"}}\n"}
{"name": "mailerlite", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: mailerlite_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"dc3b9003-2432-4e93-a7f4-4620b0f14674\"}}\n"}
{"name": "mailersend", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: mailersend_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"2707d529-3c04-46eb-9c7e-40d4038df6f7\"}}\n"}
{"name": "mailjet-mail", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: mailjet-mail_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"56582331-5de2-476b-b913-5798de77bbdf\"}}\n"}
{"name": "merge", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: merge_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"23240e9e-d14a-43bc-899f-72ea304d1994\"}}\n"}
{"name": "microsoft-onedrive", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: microsoft-onedrive_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"microsoft-onedrive\"}}\n"}
{"name": "microsoft-sharepoint", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: microsoft-sharepoint_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"microsoft-sharepoint\"}}\n"}
{"name": "n8n", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: n8n_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"4a961f66-5e99-4430-8320-a73afe52f7a2\"}}\n"}
{"name": "nasa", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: nasa_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"1a8667d7-7978-43cd-ba4d-d32cbd478971\"}}\n"}
{"name": "news-api", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: news-api_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"df38991e-f35b-4af2-996d-36817f614587\"}}\n"}
{"name": "newsdata", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: newsdata_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"60bd11d8-2632-4daa-a688-b47336d32093\"}}\n"}
{"name": "open-exchange-rates", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: open-exchange-rates_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"77d5ca6b-d345-4dce-ba1e-1935a75778b8\"}}\n"}
{"name": "opsgenie", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: opsgenie_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"06bdb480-2598-40b8-8b0f-fc2e2d2abdda\"}}\n"}
{"name": "outbrain-amplify", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: outbrain-amplify_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"outbrain-amplify\"}}\n"}
{"name": "pagerduty", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: pagerduty_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"pagerduty\"}}\n"}
{"name": "pipedrive", "config_path": "oauth_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: pipedrive_oauth_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'api_token' not found \"}}\n"}
{"name": "pivotal-tracker", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: pivotal-tracker_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"d60f5393-f99e-4310-8d05-b1876820f40e\"}}\n"}
{"name": "plaid", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: plaid_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"ed799e2b-2158-4c66-8da4-b40fe63bc72a\"}}\n"}
{"name": "primetric", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: primetric_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"f636c3c6-4077-45ac-b109-19fc62a283c1\"}}\n"}
{"name": "qonto", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: qonto_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"f7c0b910-5f66-11ed-9b6a-0242ac120002\"}}\n"}
{"name": "rd-station-marketing", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: rd-station-marketing_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"fb141f29-be2a-450b-a4f2-2cd203a00f84\"}}\n"}
{"name": "reply-io", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: reply-io_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"8cc6537e-f8a6-423c-b960-e927af76116e\"}}\n"}
{"name": "ringcentral", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: ringcentral_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"213d69b9-da66-419e-af29-c23142d4af5f\"}}\n"}
{"name": "rocket-chat", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: rocket-chat_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"921d9608-3915-450b-8078-0af18801ea1b\"}}\n"}
{"name": "s3", "config_path": "legacy_csv_with_null_bools_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: s3_legacy_csv_with_null_bools_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'streams' not found, $: required property 'bucket' not found \"}}\n"}
{"name": "s3", "config_path": "legacy_avro_duration_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: s3_legacy_avro_duration_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'streams' not found, $: required property 'bucket' not found \"}}\n"}
{"name": "s3", "config_path": "legacy_csv_custom_format_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: s3_legacy_csv_custom_format_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'streams' not found, $: required property 'bucket' not found \"}}\n"}
{"name": "s3", "config_path": "legacy_csv_user_schema_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: s3_legacy_csv_user_schema_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'streams' not found, $: required property 'bucket' not found \"}}\n"}
{"name": "s3", "config_path": "legacy_csv_skip_rows_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: s3_legacy_csv_skip_rows_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'streams' not found, $: required property 'bucket' not found \"}}\n"}
{"name": "s3", "config_path": "legacy_csv_with_nulls_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: s3_legacy_csv_with_nulls_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'streams' not found, $: required property 'bucket' not found \"}}\n"}
{"name": "s3", "config_path": "legacy_csv_skip_rows_no_header_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: s3_legacy_csv_skip_rows_no_header_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'streams' not found, $: required property 'bucket' not found \"}}\n"}
{"name": "s3", "config_path": "legacy_csv_custom_encoding_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: s3_legacy_csv_custom_encoding_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'streams' not found, $: required property 'bucket' not found \"}}\n"}
{"name": "s3", "config_path": "legacy_avro_decimal_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: s3_legacy_avro_decimal_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'streams' not found, $: required property 'bucket' not found \"}}\n"}
{"name": "s3", "config_path": "legacy_csv_user_schema_cast_complex.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: s3_legacy_csv_user_schema_cast_complex: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'streams' not found, $: required property 'bucket' not found \"}}\n"}
{"name": "s3", "config_path": "parquet_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: s3_parquet_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'streams' not found, $: required property 'bucket' not found \"}}\n"}
{"name": "s3", "config_path": "legacy_parquet_decimal_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: s3_legacy_parquet_decimal_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'streams' not found, $: required property 'bucket' not found \"}}\n"}
{"name": "s3", "config_path": "legacy_csv_no_header_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: s3_legacy_csv_no_header_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'streams' not found, $: required property 'bucket' not found \"}}\n"}
{"name": "s3", "config_path": "v4_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: s3_v4_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $.streams[0].validation_policy: does not have a value in the enumeration [Emit Record, Skip Record, Wait for Discover], $.streams[0]: required property 'format' not found \"}}\n"}
{"name": "s3", "config_path": "legacy_parquet_duration_list_struct_config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: s3_legacy_parquet_duration_list_struct_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'streams' not found, $: required property 'bucket' not found \"}}\n"}
{"name": "search-metrics", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: search-metrics_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"8d7ef552-2c0f-11ec-8d3d-0242ac130003\"}}\n"}
{"name": "serpstat", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: serpstat_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"serpstat\"}}\n"}
{"name": "statuspage", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: statuspage_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"74cbd708-46c3-4512-9c93-abd5c3e9a94d\"}}\n"}
{"name": "strava", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: strava_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $.start_date: does not match the date-time pattern must be a valid RFC 3339 date-time \"}}\n"}
{"name": "surveycto", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: surveycto_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"dd4632f4-15e0-4649-9b71-41719fb1fdee\"}}\n"}
{"name": "talkdesk-explore", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: talkdesk-explore_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"f00d2cf4-3c28-499a-ba93-b50b6f26359e\"}}\n"}
{"name": "timely", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: timely_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"bc617b5f-1b9e-4a2d-bebe-782fd454a771\"}}\n"}
{"name": "tmdb", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: tmdb_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"6240848f-f795-45eb-8f5e-c7542822fc03\"}}\n"}
{"name": "toggl", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: toggl_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"7e7c844f-2300-4342-b7d3-6dd7992593cd\"}}\n"}
{"name": "typeform", "config_path": "config_token.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: typeform_config_token: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $.credentials: must be valid to one and only one schema, but 0 are valid, $.credentials: required property 'client_id' not found, $.credentials: required property 'client_secret' not found, $.credentials: required property 'refresh_token' not found, $.credentials: required property 'access_token' not found, $.credentials: required property 'token_expiry_date' not found, $.credentials: required property 'access_token' not found \"}}\n"}
{"name": "unleash", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: unleash_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"f77914a1-442b-4195-9355-8810a1f4ed3f\"}}\n"}
{"name": "visma-economic", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: visma-economic_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"42495935-95de-4f5c-ae08-8fac00f6b308\"}}\n"}
{"name": "weatherstack", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: weatherstack_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"5db8292c-5f5a-11ed-9b6a-0242ac120002\"}}\n"}
{"name": "wrike", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: wrike_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"9c13f986-a13b-4988-b808-4705badf71c2\"}}\n"}
{"name": "xero", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: xero_config: {\"status\":422,\"type\":\"https://reference.airbyte.com/reference/errors#unprocessable-entity\",\"title\":\"unprocessable-entity\",\"detail\":\"The body of the request was not understood\",\"documentationUrl\":null,\"data\":{\"message\":\"json schema validation failed when comparing the data to the json schema. \\nErrors: $: required property 'authentication' not found \"}}\n"}
{"name": "yahoo-finance-price", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: yahoo-finance-price_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors\",\"title\":\"value-not-found\",\"detail\":\"The submitted value could not be found.\",\"documentationUrl\":null,\"data\":{\"value\":\"yahoo-finance-price\"}}\n"}
{"name": "zapier-supported-storage", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: zapier-supported-storage_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"b8c917bc-7d1b-4828-995f-6726820266d0\"}}\n"}
{"name": "zenefits", "config_path": "config.json", "error": "Traceback (most recent call last):\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 137, in create_python_source_connectors_with_sandboxes\n    source = await create_source(source_name, CONNECTORS_DIR / connector_dir / \"secrets\" / config_path, session)\n  File \"/Users/catherine/airbyte_repos/airbyte/tools/bin/make_connections_from_sandbox_accounts/./make_connections_from_sandbox_accounts.py\", line 64, in create_source\n    raise ValueError(f\"{source_connection_name}: {await response.text()}\")\nValueError: zenefits_config: {\"status\":400,\"type\":\"https://reference.airbyte.com/reference/errors#resource-not-found\",\"title\":\"resource-not-found\",\"detail\":\"The requested resource could not be found.\",\"documentationUrl\":null,\"data\":{\"resourceType\":\"STANDARD_SOURCE_DEFINITION\",\"resourceId\":\"8baba53d-2fe3-4e33-bc85-210d0eb62884\"}}\n"}
